# Generated by Django 4.1.7 on 2024-04-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=2500, null=True)),
                ('lastname', models.CharField(max_length=250, null=True)),
                ('Phonenumber', models.CharField(max_length=255, null=True)),
                ('Email_Id', models.EmailField(max_length=250, null=True)),
                ('country', models.CharField(max_length=250, null=True)),
                ('subject', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='Images/user')),
                ('status', models.CharField(default='pending', max_length=255, null=True)),
                ('Emotion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=100, null=True)),
                ('review', models.CharField(max_length=225, null=True)),
                ('sentiment', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
    ]
