# Generated by Django 4.1.7 on 2023-07-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250)),
                ('Video_Url', models.CharField(max_length=250)),
                ('Emotions', models.CharField(max_length=250)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
