# Generated by Django 4.1.7 on 2024-04-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='Video_Url',
            new_name='Url',
        ),
    ]
