# Generated by Django 4.1.7 on 2024-04-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='Images/emotions')),
                ('emotions', models.TextField(max_length=25, null=True)),
            ],
            options={
                'db_table': 'Emotion_data',
            },
        ),
    ]
